//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPENSES
    {
        public int ID { get; set; }
        public string ExpensesName { get; set; }
        public decimal CostOfExpenses { get; set; }
        public string Note { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> SaleID { get; set; }
    }
}
