//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFIT
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int SalesID { get; set; }
        public decimal OriginalPrice { get; set; }
        public decimal SalesPrice { get; set; }
        public decimal Discount { get; set; }
        public decimal CostOfExpenses { get; set; }
        public Nullable<decimal> Profit1 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
