//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASES
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int SupplierID { get; set; }
        public int CategoryID { get; set; }
        public int PurchaseSalesAmout { get; set; }
        public int PurchaseSalesPrice { get; set; }
        public Nullable<long> Total { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
